version: '3.7'
services:
  {% include "_cctmp/dash_name.txt" %}:
    command: tail -f /dev/null
    volumes:
      - {% include "_cctmp/dash_name.txt" %}-sync:/var/task:nocopy
volumes:
  {% include "_cctmp/dash_name.txt" %}-sync:
    external: true
